import turtle
# import time
t = turtle.Turtle()
t.shape("turtle")
# time.sleep(5)
t.forward(100)
# time.sleep(5)
t.left(120)
# time.sleep(5)
t.forward(100)
# time.sleep(5)
t.left(120)
# time.sleep(5)
t.forward(100)
# time.sleep(5)